version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - autoboxer
  assignees:
  - autoboxer
  ignore:
  - dependency-name: stripe
    versions:
    - 8.132.0
    - 8.133.0
    - 8.134.0
    - 8.135.0
    - 8.136.0
    - 8.137.0
    - 8.138.0
    - 8.139.0
    - 8.140.0
    - 8.141.0
    - 8.142.0
    - 8.143.0
    - 8.145.0
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: express-handlebars
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: gifsicle
    versions:
    - 5.1.0
