language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"

before_script:
  - npm install -g gulp

script: gulp

sudo: required

notifications:
  email:
    - jared.j.collier@gmail.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules