language: node_js
node_js:
  - "6.12.3"
  - "6.10.5"

before_script:
  - npm install -g gulp
  - npm rebuild node-sass

script: gulp

sudo: required

notifications:
  email:
    - jared.j.collier@gmail.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules