language: node_js
node_js:
  - "12.3.1"

sudo: false

before_script:
  - npm install -g gulp
  - npm rebuild node-sass

script: gulp travis

notifications:
  email:
    - jared.j.collier@gmail.com

services:
  - mongodb

cache:
  npm: true
  directories:
    - "node_modules"