language: node_js
node_js:
  - "11.14.0"
sudo: false
before_script:
  - npm install -g gulp
  - npm rebuild node-sass
notifications:
  email:
    - jared.j.collier@gmail.com
services:
  - mongodb
git:
  depth:
    10
cache:
  # cache $HOME/.npm when npm ci is default script command
  # cache node_modules in all other cases
  npm: true
  directories:
    # cache the folder with the Cypress binary
    - ~/.cache
install:
  - npm ci
script:
  - gulp travis
  - $(npm bin)/cypress run --record --key ec953034-c177-4f0d-85c5-175ecb8604a8