var dataMigrationService	= require('../service_data-migration'),
	async					= require('async');

exports.getStatesMap = function getStatesMap(req, res, done) {

	var locals = res.locals;

	async.parallel([
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Alabama', returnTarget: 'stateAL'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Alaska', returnTarget: 'stateAK'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Arizona', returnTarget: 'stateAZ'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Arkansas', returnTarget: 'stateAR'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'California', returnTarget: 'stateCA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Colorado', returnTarget: 'stateCO'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Connecticut', returnTarget: 'stateCT'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Delaware', returnTarget: 'stateDE'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Florida', returnTarget: 'stateFL'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Georgia', returnTarget: 'stateGA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Hawaii', returnTarget: 'stateHI'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Idaho', returnTarget: 'stateID'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Illinois', returnTarget: 'stateIL'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Indiana', returnTarget: 'stateIN'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Iowa', returnTarget: 'stateIA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Kansas', returnTarget: 'stateKS'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Kentucky', returnTarget: 'stateKY'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Louisiana', returnTarget: 'stateLA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Maine', returnTarget: 'stateME'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Maryland', returnTarget: 'stateMD'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Massachusetts', returnTarget: 'stateMA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Michigan', returnTarget: 'stateMI'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Minnesota', returnTarget: 'stateMN'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Mississippi', returnTarget: 'stateMS'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Missouri', returnTarget: 'stateMO'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Montana', returnTarget: 'stateMT'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Nebraska', returnTarget: 'stateNE'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Nevada', returnTarget: 'stateNV'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'New Hampshire', returnTarget: 'stateNH'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'New Jersey', returnTarget: 'stateNJ'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'New Mexico', returnTarget: 'stateNM'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'New York', returnTarget: 'stateNY'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'North Carolina', returnTarget: 'stateNC' }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'North Dakota', returnTarget: 'stateND'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Ohio', returnTarget: 'stateOH'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Oklahoma', returnTarget: 'stateOK'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Oregon', returnTarget: 'stateOR'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Pennsylvania', returnTarget: 'statePA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Rhode Island', returnTarget: 'stateRI'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'South Carolina', returnTarget: 'stateSC'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'South Dakota', returnTarget: 'stateSD'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Tennessee', returnTarget: 'stateTN'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Texas', returnTarget: 'stateTX'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Utah', returnTarget: 'stateUT'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Vermont', returnTarget: 'stateVT'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Virginia', returnTarget: 'stateVA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Washington', returnTarget: 'stateWA'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'West Virginia', returnTarget: 'stateWV'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Wisconsin', returnTarget: 'stateWI'  }); },
		function(done) { dataMigrationService.getModelId(req, res, done, { model: 'State', targetField: 'state', targetValue: 'Wyoming', returnTarget: 'stateWY'  }); }


	], function() {

		locals.statesMap = {
			"AL" : locals.stateAL,
			"AK" : locals.stateAK,
			"AZ" : locals.stateAZ,
			"AR" : locals.stateAR,
			"CA" : locals.stateCA,
			"CO" : locals.stateCO,
			"CT" : locals.stateCT,
			"DE" : locals.stateDE,
			"FL" : locals.stateFL,
			"GA" : locals.stateGA,
			"HI" : locals.stateHI,
			"ID" : locals.stateID,
			"IL" : locals.stateIL,
			"IN" : locals.stateIN,
			"IA" : locals.stateIA,
			"KS" : locals.stateKS,
			"KY" : locals.stateKY,
			"LA" : locals.stateLA,
			"ME" : locals.stateME,
			"MD" : locals.stateMD,
			"MA": locals.stateMA,
			"MI": locals.stateMI,
			"MN": locals.stateMN,
			"MS": locals.stateMS,
			"MO": locals.stateMO,
			"MT": locals.stateMT,
			"NE": locals.stateNE,
			"NV": locals.stateNV,
			"NH": locals.stateNH,
			"NJ": locals.stateNJ,
			"NM": locals.stateNM,
			"NY": locals.stateNY,
			"NC": locals.stateNC,
			"ND": locals.stateND,
			"OH": locals.stateOH,
			"OK": locals.stateOK,
			"OR": locals.stateOR,
			"PA": locals.statePA,
			"RI": locals.stateRI,
			"SC": locals.stateSC,
			"SD": locals.stateSD,
			"TN": locals.stateTN,
			"TX": locals.stateTX,
			"UT": locals.stateUT,
			"VT": locals.stateVT,
			"VA": locals.stateVA,
			"WA": locals.stateWA,
			"WV": locals.stateWV,
			"WI": locals.stateWI,
			"WY": locals.stateWY
		};

		done();
	});
}
